### ISSUE TITLE
HomeKit Secure Video

### ISSUE THREAD

**Issue by Robert91112** [Brandawg93/homebridge-nest-cam2#19]
Would it be possible?  

https://github.com/KhaosT/homebridge-camera-ffmpeg/issues/338

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Brandawg93** [comment]
According to [this](https://www.apple.com/ios/home/accessories/#section-camera), I don’t think so. The camera must be “HomeKit certified” and if you look at the camera’s settings it says it is not HomeKit certified. Also, it would probably kill Raspberry Pis and other small devices running Homebridge because they would have to transcode 24/7 to upload to iCloud.

**Comment by Robert91112** [comment]
https://github.com/KhaosT/HAP-NodeJS/issues/741 

These guys seem to be working on it for ip cameras through HAP.  I don’t know enough about coding to fully understand it.  But they seem to be getting around the certified part.   I think a lot of people would be interested in this, even if it did take some beefier hardware.  

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Brandawg93** [comment]
Great thread! I'll look into it.

**Comment by Brandawg93** [comment]
After much consideration, I've decided to not include HomeKit Secure Video into this plugin as it would break Nest Lab's [End User License Agreement](https://nest.com/legal/eula/). Since Nest sells a subscription plan for cloud storage, I wouldn't want others to get penalized for circumventing that plan.

**Comment by taglia** [comment]
Which part of the EULA would be breached by this? I checked but couldn't find the problem. I am asking because Nest does not sell their cloud storage plan in every country (usually you find this out once you have already bought the cameras…). Some of us can't buy the subscription even if we wanted.
