### ISSUE TITLE
Hardware transcoding inside docker

### ISSUE THREAD

**Issue by nope89** [Brandawg93/homebridge-nest-cam2#22]
Hi, I'm fan of your plugin. But the streaming on my RPi with plugin installed inside my docker is not working well. It starts to stream the video but stalls after a short amount of time. I'd like to know if there is a possibility to use hardware transcoding within a docker?

**Comment by Brandawg93** [comment]
I am running the plugin on an RPi 4 inside docker with no issues. It could be the type of Pi you have. Unfortunately, hardware transcoding inside docker defeats the purpose of docker. Docker is designed to isolate the container from the rest of the OS. The ffmpeg inside the container is a special version that allows it to work but will not work with hardware transcoding because it needs to be able to work on many different OSes. There isn't much I can do from my end, but you can try submitting an issue with the [creator of the container](https://github.com/oznu/homebridge-config-ui-x).

**Comment by nope89** [comment]
From wat I remember it is a RPi 3+, probably a big difference already next to the newer 4. I might will ask the docker creator. Thanks for your reply!

**Comment by Brandawg93** [comment]
v1.1.8 may fix your issue as it adds static binaries for RPi hardware transcoding, but if not there is not much else I can do since the issue lies with docker. If you hear back from the docker maintainer, let us know here.
